const baseImageUrl = "./images/";

const units = [

{ id: 1, name: "001", attribute: "Technique", image: baseImageUrl + "001 - Technique.png" },
  { id: 2, name: "001", attribute: "Instinct", image: baseImageUrl + "001 - Instinct.png" },
  { id: 3, name: "001", attribute: "Force", image: baseImageUrl + "001 - Force.png" },
  { id: 4, name: "001", attribute: "Vitesse", image: baseImageUrl + "001 - Vitesse.png" },
  { id: 5, name: "001", attribute: "Connaissance", image: baseImageUrl + "001 - Connaissance.png" },

  { id: 6, name: "002", attribute: "Technique", image: baseImageUrl + "002 - Technique.png" },
  { id: 7, name: "002", attribute: "Instinct", image: baseImageUrl + "002 - Instinct.png" },
  { id: 8, name: "002", attribute: "Force", image: baseImageUrl + "002 - Force.png" },
  { id: 9, name: "002", attribute: "Vitesse", image: baseImageUrl + "002 - Vitesse.png" },
  { id: 10, name: "002", attribute: "Connaissance", image: baseImageUrl + "002 - Connaissance.png" },

  { id: 11, name: "003", attribute: "Technique", image: baseImageUrl + "003 - Technique.png" },
  { id: 12, name: "003", attribute: "Instinct", image: baseImageUrl + "003 - Instinct.png" },
  { id: 13, name: "003", attribute: "Force", image: baseImageUrl + "003 - Force.png" },
  { id: 14, name: "003", attribute: "Vitesse", image: baseImageUrl + "003 - Vitesse.png" },
  { id: 15, name: "003", attribute: "Connaissance", image: baseImageUrl + "003 - Connaissance.png" },

  { id: 16, name: "004", attribute: "Technique", image: baseImageUrl + "004 - Technique.png" },
  { id: 17, name: "004", attribute: "Instinct", image: baseImageUrl + "004 - Instinct.png" },
  { id: 18, name: "004", attribute: "Force", image: baseImageUrl + "004 - Force.png" },
  { id: 19, name: "004", attribute: "Vitesse", image: baseImageUrl + "004 - Vitesse.png" },
  { id: 20, name: "004", attribute: "Connaissance", image: baseImageUrl + "004 - Connaissance.png" },

  { id: 21, name: "005", attribute: "Technique", image: baseImageUrl + "005 - Technique.png" },
  { id: 22, name: "005", attribute: "Instinct", image: baseImageUrl + "005 - Instinct.png" },
  { id: 23, name: "005", attribute: "Force", image: baseImageUrl + "005 - Force.png" },
  { id: 24, name: "005", attribute: "Vitesse", image: baseImageUrl + "005 - Vitesse.png" },
  { id: 25, name: "005", attribute: "Connaissance", image: baseImageUrl + "005 - Connaissance.png" },

  { id: 26, name: "006", attribute: "Technique", image: baseImageUrl + "006 - Technique.png" },
  { id: 27, name: "006", attribute: "Instinct", image: baseImageUrl + "006 - Instinct.png" },
  { id: 28, name: "006", attribute: "Force", image: baseImageUrl + "006 - Force.png" },
  { id: 29, name: "006", attribute: "Vitesse", image: baseImageUrl + "006 - Vitesse.png" },
  { id: 30, name: "006", attribute: "Connaissance", image: baseImageUrl + "006 - Connaissance.png" },

  { id: 31, name: "007", attribute: "Technique", image: baseImageUrl + "007 - Technique.png" },
  { id: 32, name: "007", attribute: "Instinct", image: baseImageUrl + "007 - Instinct.png" },
  { id: 33, name: "007", attribute: "Force", image: baseImageUrl + "007 - Force.png" },
  { id: 34, name: "007", attribute: "Vitesse", image: baseImageUrl + "007 - Vitesse.png" },
  { id: 35, name: "007", attribute: "Connaissance", image: baseImageUrl + "007 - Connaissance.png" },

  { id: 36, name: "008", attribute: "Technique", image: baseImageUrl + "008 - Technique.png" },
  { id: 37, name: "008", attribute: "Instinct", image: baseImageUrl + "008 - Instinct.png" },
  { id: 38, name: "008", attribute: "Force", image: baseImageUrl + "008 - Force.png" },
  { id: 39, name: "008", attribute: "Vitesse", image: baseImageUrl + "008 - Vitesse.png" },
  { id: 40, name: "008", attribute: "Connaissance", image: baseImageUrl + "008 - Connaissance.png" },

  { id: 41, name: "009", attribute: "Technique", image: baseImageUrl + "009 - Technique.png" },
  { id: 42, name: "009", attribute: "Instinct", image: baseImageUrl + "009 - Instinct.png" },
  { id: 43, name: "009", attribute: "Force", image: baseImageUrl + "009 - Force.png" },
  { id: 44, name: "009", attribute: "Vitesse", image: baseImageUrl + "009 - Vitesse.png" },
  { id: 45, name: "009", attribute: "Connaissance", image: baseImageUrl + "009 - Connaissance.png" },

  { id: 46, name: "010", attribute: "Technique", image: baseImageUrl + "010 - Technique.png" },
  { id: 47, name: "010", attribute: "Instinct", image: baseImageUrl + "010 - Instinct.png" },
  { id: 48, name: "010", attribute: "Force", image: baseImageUrl + "010 - Force.png" },
  { id: 49, name: "010", attribute: "Vitesse", image: baseImageUrl + "010 - Vitesse.png" },
  { id: 50, name: "010", attribute: "Connaissance", image: baseImageUrl + "010 - Connaissance.png" },

  { id: 51, name: "011", attribute: "Technique", image: baseImageUrl + "011 - Technique.png" },
  { id: 52, name: "011", attribute: "Instinct", image: baseImageUrl + "011 - Instinct.png" },
  { id: 53, name: "011", attribute: "Force", image: baseImageUrl + "011 - Force.png" },
  { id: 54, name: "011", attribute: "Vitesse", image: baseImageUrl + "011 - Vitesse.png" },
  { id: 55, name: "011", attribute: "Connaissance", image: baseImageUrl + "011 - Connaissance.png" },

  { id: 56, name: "012", attribute: "Technique", image: baseImageUrl + "012 - Technique.png" },
  { id: 57, name: "012", attribute: "Instinct", image: baseImageUrl + "012 - Instinct.png" },
  { id: 58, name: "012", attribute: "Force", image: baseImageUrl + "012 - Force.png" },
  { id: 59, name: "012", attribute: "Vitesse", image: baseImageUrl + "012 - Vitesse.png" },
  { id: 60, name: "012", attribute: "Connaissance", image: baseImageUrl + "012 - Connaissance.png" },

  { id: 61, name: "013", attribute: "Technique", image: baseImageUrl + "013 - Technique.png" },
  { id: 62, name: "013", attribute: "Instinct", image: baseImageUrl + "013 - Instinct.png" },
  { id: 63, name: "013", attribute: "Force", image: baseImageUrl + "013 - Force.png" },
  { id: 64, name: "013", attribute: "Vitesse", image: baseImageUrl + "013 - Vitesse.png" },
  { id: 65, name: "013", attribute: "Connaissance", image: baseImageUrl + "013 - Connaissance.png" },

  { id: 66, name: "014", attribute: "Technique", image: baseImageUrl + "014 - Technique.png" },
  { id: 67, name: "014", attribute: "Instinct", image: baseImageUrl + "014 - Instinct.png" },
  { id: 68, name: "014", attribute: "Force", image: baseImageUrl + "014 - Force.png" },
  { id: 69, name: "014", attribute: "Vitesse", image: baseImageUrl + "014 - Vitesse.png" },
  { id: 70, name: "014", attribute: "Connaissance", image: baseImageUrl + "014 - Connaissance.png" },

  { id: 71, name: "015", attribute: "Technique", image: baseImageUrl + "015 - Technique.png" },
  { id: 72, name: "015", attribute: "Instinct", image: baseImageUrl + "015 - Instinct.png" },
  { id: 73, name: "015", attribute: "Force", image: baseImageUrl + "015 - Force.png" },
  { id: 74, name: "015", attribute: "Vitesse", image: baseImageUrl + "015 - Vitesse.png" },
  { id: 75, name: "015", attribute: "Connaissance", image: baseImageUrl + "015 - Connaissance.png" },

  { id: 76, name: "016", attribute: "Technique", image: baseImageUrl + "016 - Technique.png" },
  { id: 77, name: "016", attribute: "Instinct", image: baseImageUrl + "016 - Instinct.png" },
  { id: 78, name: "016", attribute: "Force", image: baseImageUrl + "016 - Force.png" },
  { id: 79, name: "016", attribute: "Vitesse", image: baseImageUrl + "016 - Vitesse.png" },
  { id: 80, name: "016", attribute: "Connaissance", image: baseImageUrl + "016 - Connaissance.png" },

  { id: 81, name: "017", attribute: "Technique", image: baseImageUrl + "017 - Technique.png" },
  { id: 82, name: "017", attribute: "Instinct", image: baseImageUrl + "017 - Instinct.png" },
  { id: 83, name: "017", attribute: "Force", image: baseImageUrl + "017 - Force.png" },
  { id: 84, name: "017", attribute: "Vitesse", image: baseImageUrl + "017 - Vitesse.png" },
  { id: 85, name: "017", attribute: "Connaissance", image: baseImageUrl + "017 - Connaissance.png" },

  { id: 86, name: "018", attribute: "Technique", image: baseImageUrl + "018 - Technique.png" },
  { id: 87, name: "018", attribute: "Instinct", image: baseImageUrl + "018 - Instinct.png" },
  { id: 88, name: "018", attribute: "Force", image: baseImageUrl + "018 - Force.png" },
  { id: 89, name: "018", attribute: "Vitesse", image: baseImageUrl + "018 - Vitesse.png" },
  { id: 90, name: "018", attribute: "Connaissance", image: baseImageUrl + "018 - Connaissance.png" },

  { id: 91, name: "019", attribute: "Technique", image: baseImageUrl + "019 - Technique.png" },
  { id: 92, name: "019", attribute: "Instinct", image: baseImageUrl + "019 - Instinct.png" },
  { id: 93, name: "019", attribute: "Force", image: baseImageUrl + "019 - Force.png" },
  { id: 94, name: "019", attribute: "Vitesse", image: baseImageUrl + "019 - Vitesse.png" },
  { id: 95, name: "019", attribute: "Connaissance", image: baseImageUrl + "019 - Connaissance.png" },

  { id: 96, name: "020", attribute: "Technique", image: baseImageUrl + "020 - Technique.png" },
  { id: 97, name: "020", attribute: "Instinct", image: baseImageUrl + "020 - Instinct.png" },
  { id: 98, name: "020", attribute: "Force", image: baseImageUrl + "020 - Force.png" },
  { id: 99, name: "020", attribute: "Vitesse", image: baseImageUrl + "020 - Vitesse.png" },
  { id: 100, name: "020", attribute: "Connaissance", image: baseImageUrl + "020 - Connaissance.png" },

  { id: 101, name: "021", attribute: "Technique", image: baseImageUrl + "021 - Technique.png" },
  { id: 102, name: "021", attribute: "Instinct", image: baseImageUrl + "021 - Instinct.png" },
  { id: 103, name: "021", attribute: "Force", image: baseImageUrl + "021 - Force.png" },
  { id: 104, name: "021", attribute: "Vitesse", image: baseImageUrl + "021 - Vitesse.png" },
  { id: 105, name: "021", attribute: "Connaissance", image: baseImageUrl + "021 - Connaissance.png" },

  { id: 106, name: "022", attribute: "Technique", image: baseImageUrl + "022 - Technique.png" },
  { id: 107, name: "022", attribute: "Instinct", image: baseImageUrl + "022 - Instinct.png" },
  { id: 108, name: "022", attribute: "Force", image: baseImageUrl + "022 - Force.png" },
  { id: 109, name: "022", attribute: "Vitesse", image: baseImageUrl + "022 - Vitesse.png" },
  { id: 110, name: "022", attribute: "Connaissance", image: baseImageUrl + "022 - Connaissance.png" },

  { id: 111, name: "023", attribute: "Technique", image: baseImageUrl + "023 - Technique.png" },
  { id: 112, name: "023", attribute: "Instinct", image: baseImageUrl + "023 - Instinct.png" },
  { id: 113, name: "023", attribute: "Force", image: baseImageUrl + "023 - Force.png" },
  { id: 114, name: "023", attribute: "Vitesse", image: baseImageUrl + "023 - Vitesse.png" },
  { id: 115, name: "023", attribute: "Connaissance", image: baseImageUrl + "023 - Connaissance.png" },

  { id: 116, name: "024", attribute: "Technique", image: baseImageUrl + "024 - Technique.png" },
  { id: 117, name: "024", attribute: "Instinct", image: baseImageUrl + "024 - Instinct.png" },
  { id: 118, name: "024", attribute: "Force", image: baseImageUrl + "024 - Force.png" },
  { id: 119, name: "024", attribute: "Vitesse", image: baseImageUrl + "024 - Vitesse.png" },
  { id: 120, name: "024", attribute: "Connaissance", image: baseImageUrl + "024 - Connaissance.png" },

  { id: 121, name: "025", attribute: "Technique", image: baseImageUrl + "025 - Technique.png" },
  { id: 122, name: "025", attribute: "Instinct", image: baseImageUrl + "025 - Instinct.png" },
  { id: 123, name: "025", attribute: "Force", image: baseImageUrl + "025 - Force.png" },
  { id: 124, name: "025", attribute: "Vitesse", image: baseImageUrl + "025 - Vitesse.png" },
  { id: 125, name: "025", attribute: "Connaissance", image: baseImageUrl + "025 - Connaissance.png" },

  { id: 126, name: "026", attribute: "Technique", image: baseImageUrl + "026 - Technique.png" },
  { id: 127, name: "026", attribute: "Instinct", image: baseImageUrl + "026 - Instinct.png" },
  { id: 128, name: "026", attribute: "Force", image: baseImageUrl + "026 - Force.png" },
  { id: 129, name: "026", attribute: "Vitesse", image: baseImageUrl + "026 - Vitesse.png" },
  { id: 130, name: "026", attribute: "Connaissance", image: baseImageUrl + "026 - Connaissance.png" },

  { id: 131, name: "027", attribute: "Technique", image: baseImageUrl + "027 - Technique.png" },
  { id: 132, name: "027", attribute: "Instinct", image: baseImageUrl + "027 - Instinct.png" },
  { id: 133, name: "027", attribute: "Force", image: baseImageUrl + "027 - Force.png" },
  { id: 134, name: "027", attribute: "Vitesse", image: baseImageUrl + "027 - Vitesse.png" },
  { id: 135, name: "027", attribute: "Connaissance", image: baseImageUrl + "027 - Connaissance.png" },

  { id: 136, name: "028", attribute: "Technique", image: baseImageUrl + "028 - Technique.png" },
  { id: 137, name: "028", attribute: "Instinct", image: baseImageUrl + "028 - Instinct.png" },
  { id: 138, name: "028", attribute: "Force", image: baseImageUrl + "028 - Force.png" },
  { id: 139, name: "028", attribute: "Vitesse", image: baseImageUrl + "028 - Vitesse.png" },
  { id: 140, name: "028", attribute: "Connaissance", image: baseImageUrl + "028 - Connaissance.png" },

  { id: 141, name: "029", attribute: "Technique", image: baseImageUrl + "029 - Technique.png" },
  { id: 142, name: "029", attribute: "Instinct", image: baseImageUrl + "029 - Instinct.png" },
  { id: 143, name: "029", attribute: "Force", image: baseImageUrl + "029 - Force.png" },
  { id: 144, name: "029", attribute: "Vitesse", image: baseImageUrl + "029 - Vitesse.png" },
  { id: 145, name: "029", attribute: "Connaissance", image: baseImageUrl + "029 - Connaissance.png" },

  { id: 146, name: "030", attribute: "Technique", image: baseImageUrl + "030 - Technique.png" },
  { id: 147, name: "030", attribute: "Instinct", image: baseImageUrl + "030 - Instinct.png" },
  { id: 148, name: "030", attribute: "Force", image: baseImageUrl + "030 - Force.png" },
  { id: 149, name: "030", attribute: "Vitesse", image: baseImageUrl + "030 - Vitesse.png" },
  { id: 150, name: "030", attribute: "Connaissance", image: baseImageUrl + "030 - Connaissance.png" },

  { id: 151, name: "031", attribute: "Technique", image: baseImageUrl + "031 - Technique.png" },
  { id: 152, name: "031", attribute: "Instinct", image: baseImageUrl + "031 - Instinct.png" },
  { id: 153, name: "031", attribute: "Force", image: baseImageUrl + "031 - Force.png" },
  { id: 154, name: "031", attribute: "Vitesse", image: baseImageUrl + "031 - Vitesse.png" },
  { id: 155, name: "031", attribute: "Connaissance", image: baseImageUrl + "031 - Connaissance.png" },

  { id: 156, name: "032", attribute: "Technique", image: baseImageUrl + "032 - Technique.png" },
  { id: 157, name: "032", attribute: "Instinct", image: baseImageUrl + "032 - Instinct.png" },
  { id: 158, name: "032", attribute: "Force", image: baseImageUrl + "032 - Force.png" },
  { id: 159, name: "032", attribute: "Vitesse", image: baseImageUrl + "032 - Vitesse.png" },
  { id: 160, name: "032", attribute: "Connaissance", image: baseImageUrl + "032 - Connaissance.png" },

  { id: 161, name: "033", attribute: "Technique", image: baseImageUrl + "033 - Technique.png" },
  { id: 162, name: "033", attribute: "Instinct", image: baseImageUrl + "033 - Instinct.png" },
  { id: 163, name: "033", attribute: "Force", image: baseImageUrl + "033 - Force.png" },
  { id: 164, name: "033", attribute: "Vitesse", image: baseImageUrl + "033 - Vitesse.png" },
  { id: 165, name: "033", attribute: "Connaissance", image: baseImageUrl + "033 - Connaissance.png" },

  { id: 166, name: "034", attribute: "Technique", image: baseImageUrl + "034 - Technique.png" },
  { id: 167, name: "034", attribute: "Instinct", image: baseImageUrl + "034 - Instinct.png" },
  { id: 168, name: "034", attribute: "Force", image: baseImageUrl + "034 - Force.png" },
  { id: 169, name: "034", attribute: "Vitesse", image: baseImageUrl + "034 - Vitesse.png" },
  { id: 170, name: "034", attribute: "Connaissance", image: baseImageUrl + "034 - Connaissance.png" },

  { id: 171, name: "035", attribute: "Technique", image: baseImageUrl + "035 - Technique.png" },
  { id: 172, name: "035", attribute: "Instinct", image: baseImageUrl + "035 - Instinct.png" },
  { id: 173, name: "035", attribute: "Force", image: baseImageUrl + "035 - Force.png" },
  { id: 174, name: "035", attribute: "Vitesse", image: baseImageUrl + "035 - Vitesse.png" },
  { id: 175, name: "035", attribute: "Connaissance", image: baseImageUrl + "035 - Connaissance.png" },

  { id: 176, name: "036", attribute: "Technique", image: baseImageUrl + "036 - Technique.png" },
  { id: 177, name: "036", attribute: "Instinct", image: baseImageUrl + "036 - Instinct.png" },
  { id: 178, name: "036", attribute: "Force", image: baseImageUrl + "036 - Force.png" },
  { id: 179, name: "036", attribute: "Vitesse", image: baseImageUrl + "036 - Vitesse.png" },
  { id: 180, name: "036", attribute: "Connaissance", image: baseImageUrl + "036 - Connaissance.png" },

  { id: 181, name: "037", attribute: "Technique", image: baseImageUrl + "037 - Technique.png" },
  { id: 182, name: "037", attribute: "Instinct", image: baseImageUrl + "037 - Instinct.png" },
  { id: 183, name: "037", attribute: "Force", image: baseImageUrl + "037 - Force.png" },
  { id: 184, name: "037", attribute: "Vitesse", image: baseImageUrl + "037 - Vitesse.png" },
  { id: 185, name: "037", attribute: "Connaissance", image: baseImageUrl + "037 - Connaissance.png" },

  { id: 186, name: "038", attribute: "Technique", image: baseImageUrl + "038 - Technique.png" },
  { id: 187, name: "038", attribute: "Instinct", image: baseImageUrl + "038 - Instinct.png" },
  { id: 188, name: "038", attribute: "Force", image: baseImageUrl + "038 - Force.png" },
  { id: 189, name: "038", attribute: "Vitesse", image: baseImageUrl + "038 - Vitesse.png" },
  { id: 190, name: "038", attribute: "Connaissance", image: baseImageUrl + "038 - Connaissance.png" },

  { id: 191, name: "039", attribute: "Technique", image: baseImageUrl + "039 - Technique.png" },
  { id: 192, name: "039", attribute: "Instinct", image: baseImageUrl + "039 - Instinct.png" },
  { id: 193, name: "039", attribute: "Force", image: baseImageUrl + "039 - Force.png" },
  { id: 194, name: "039", attribute: "Vitesse", image: baseImageUrl + "039 - Vitesse.png" },
  { id: 195, name: "039", attribute: "Connaissance", image: baseImageUrl + "039 - Connaissance.png" },

  { id: 196, name: "040", attribute: "Technique", image: baseImageUrl + "040 - Technique.png" },
  { id: 197, name: "040", attribute: "Instinct", image: baseImageUrl + "040 - Instinct.png" },
  { id: 198, name: "040", attribute: "Force", image: baseImageUrl + "040 - Force.png" },
  { id: 199, name: "040", attribute: "Vitesse", image: baseImageUrl + "040 - Vitesse.png" },
  { id: 200, name: "040", attribute: "Connaissance", image: baseImageUrl + "040 - Connaissance.png" },

  { id: 201, name: "041", attribute: "Technique", image: baseImageUrl + "041 - Technique.png" },
  { id: 202, name: "041", attribute: "Instinct", image: baseImageUrl + "041 - Instinct.png" },
  { id: 203, name: "041", attribute: "Force", image: baseImageUrl + "041 - Force.png" },
  { id: 204, name: "041", attribute: "Vitesse", image: baseImageUrl + "041 - Vitesse.png" },
  { id: 205, name: "041", attribute: "Connaissance", image: baseImageUrl + "041 - Connaissance.png" },

  { id: 206, name: "042", attribute: "Technique", image: baseImageUrl + "042 - Technique.png" },
  { id: 207, name: "042", attribute: "Instinct", image: baseImageUrl + "042 - Instinct.png" },
  { id: 208, name: "042", attribute: "Force", image: baseImageUrl + "042 - Force.png" },
  { id: 209, name: "042", attribute: "Vitesse", image: baseImageUrl + "042 - Vitesse.png" },
  { id: 210, name: "042", attribute: "Connaissance", image: baseImageUrl + "042 - Connaissance.png" },

  { id: 211, name: "043", attribute: "Technique", image: baseImageUrl + "043 - Technique.png" },
  { id: 212, name: "043", attribute: "Instinct", image: baseImageUrl + "043 - Instinct.png" },
  { id: 213, name: "043", attribute: "Force", image: baseImageUrl + "043 - Force.png" },
  { id: 214, name: "043", attribute: "Vitesse", image: baseImageUrl + "043 - Vitesse.png" },
  { id: 215, name: "043", attribute: "Connaissance", image: baseImageUrl + "043 - Connaissance.png" },

  { id: 216, name: "044", attribute: "Technique", image: baseImageUrl + "044 - Technique.png" },
  { id: 217, name: "044", attribute: "Instinct", image: baseImageUrl + "044 - Instinct.png" },
  { id: 218, name: "044", attribute: "Force", image: baseImageUrl + "044 - Force.png" },
  { id: 219, name: "044", attribute: "Vitesse", image: baseImageUrl + "044 - Vitesse.png" },
  { id: 220, name: "044", attribute: "Connaissance", image: baseImageUrl + "044 - Connaissance.png" },

  { id: 221, name: "045", attribute: "Technique", image: baseImageUrl + "045 - Technique.png" },
  { id: 222, name: "045", attribute: "Instinct", image: baseImageUrl + "045 - Instinct.png" },
  { id: 223, name: "045", attribute: "Force", image: baseImageUrl + "045 - Force.png" },
  { id: 224, name: "045", attribute: "Vitesse", image: baseImageUrl + "045 - Vitesse.png" },
  { id: 225, name: "045", attribute: "Connaissance", image: baseImageUrl + "045 - Connaissance.png" },

  { id: 226, name: "046", attribute: "Technique", image: baseImageUrl + "046 - Technique.png" },
  { id: 227, name: "046", attribute: "Instinct", image: baseImageUrl + "046 - Instinct.png" },
  { id: 228, name: "046", attribute: "Force", image: baseImageUrl + "046 - Force.png" },
  { id: 229, name: "046", attribute: "Vitesse", image: baseImageUrl + "046 - Vitesse.png" },
  { id: 230, name: "046", attribute: "Connaissance", image: baseImageUrl + "046 - Connaissance.png" },

  { id: 231, name: "047", attribute: "Technique", image: baseImageUrl + "047 - Technique.png" },
  { id: 232, name: "047", attribute: "Instinct", image: baseImageUrl + "047 - Instinct.png" },
  { id: 233, name: "047", attribute: "Force", image: baseImageUrl + "047 - Force.png" },
  { id: 234, name: "047", attribute: "Vitesse", image: baseImageUrl + "047 - Vitesse.png" },
  { id: 235, name: "047", attribute: "Connaissance", image: baseImageUrl + "047 - Connaissance.png" },

  { id: 236, name: "048", attribute: "Technique", image: baseImageUrl + "048 - Technique.png" },
  { id: 237, name: "048", attribute: "Instinct", image: baseImageUrl + "048 - Instinct.png" },
  { id: 238, name: "048", attribute: "Force", image: baseImageUrl + "048 - Force.png" },
  { id: 239, name: "048", attribute: "Vitesse", image: baseImageUrl + "048 - Vitesse.png" },
  { id: 240, name: "048", attribute: "Connaissance", image: baseImageUrl + "048 - Connaissance.png" },

  { id: 241, name: "049", attribute: "Technique", image: baseImageUrl + "049 - Technique.png" },
  { id: 242, name: "049", attribute: "Instinct", image: baseImageUrl + "049 - Instinct.png" },
  { id: 243, name: "049", attribute: "Force", image: baseImageUrl + "049 - Force.png" },
  { id: 244, name: "049", attribute: "Vitesse", image: baseImageUrl + "049 - Vitesse.png" },
  { id: 245, name: "049", attribute: "Connaissance", image: baseImageUrl + "049 - Connaissance.png" },

  { id: 246, name: "050", attribute: "Technique", image: baseImageUrl + "050 - Technique.png" },
  { id: 247, name: "050", attribute: "Instinct", image: baseImageUrl + "050 - Instinct.png" },
  { id: 248, name: "050", attribute: "Force", image: baseImageUrl + "050 - Force.png" },
  { id: 249, name: "050", attribute: "Vitesse", image: baseImageUrl + "050 - Vitesse.png" },
  { id: 250, name: "050", attribute: "Connaissance", image: baseImageUrl + "050 - Connaissance.png" },

  { id: 251, name: "051", attribute: "Technique", image: baseImageUrl + "051 - Technique.png" },
  { id: 252, name: "051", attribute: "Instinct", image: baseImageUrl + "051 - Instinct.png" },
  { id: 253, name: "051", attribute: "Force", image: baseImageUrl + "051 - Force.png" },
  { id: 254, name: "051", attribute: "Vitesse", image: baseImageUrl + "051 - Vitesse.png" },
  { id: 255, name: "051", attribute: "Connaissance", image: baseImageUrl + "051 - Connaissance.png" },

  { id: 256, name: "052", attribute: "Technique", image: baseImageUrl + "052 - Technique.png" },
  { id: 257, name: "052", attribute: "Instinct", image: baseImageUrl + "052 - Instinct.png" },
  { id: 258, name: "052", attribute: "Force", image: baseImageUrl + "052 - Force.png" },
  { id: 259, name: "052", attribute: "Vitesse", image: baseImageUrl + "052 - Vitesse.png" },
  { id: 260, name: "052", attribute: "Connaissance", image: baseImageUrl + "052 - Connaissance.png" },

  { id: 261, name: "053", attribute: "Technique", image: baseImageUrl + "053 - Technique.png" },
  { id: 262, name: "053", attribute: "Instinct", image: baseImageUrl + "053 - Instinct.png" },
  { id: 263, name: "053", attribute: "Force", image: baseImageUrl + "053 - Force.png" },
  { id: 264, name: "053", attribute: "Vitesse", image: baseImageUrl + "053 - Vitesse.png" },
  { id: 265, name: "053", attribute: "Connaissance", image: baseImageUrl + "053 - Connaissance.png" },

  { id: 266, name: "054", attribute: "Technique", image: baseImageUrl + "054 - Technique.png" },
  { id: 267, name: "054", attribute: "Instinct", image: baseImageUrl + "054 - Instinct.png" },
  { id: 268, name: "054", attribute: "Force", image: baseImageUrl + "054 - Force.png" },
  { id: 269, name: "054", attribute: "Vitesse", image: baseImageUrl + "054 - Vitesse.png" },
  { id: 270, name: "054", attribute: "Connaissance", image: baseImageUrl + "054 - Connaissance.png" },

  { id: 271, name: "055", attribute: "Technique", image: baseImageUrl + "055 - Technique.png" },
  { id: 272, name: "055", attribute: "Instinct", image: baseImageUrl + "055 - Instinct.png" },
  { id: 273, name: "055", attribute: "Force", image: baseImageUrl + "055 - Force.png" },
  { id: 274, name: "055", attribute: "Vitesse", image: baseImageUrl + "055 - Vitesse.png" },
  { id: 275, name: "055", attribute: "Connaissance", image: baseImageUrl + "055 - Connaissance.png" },

  { id: 276, name: "056", attribute: "Technique", image: baseImageUrl + "056 - Technique.png" },
  { id: 277, name: "056", attribute: "Instinct", image: baseImageUrl + "056 - Instinct.png" },
  { id: 278, name: "056", attribute: "Force", image: baseImageUrl + "056 - Force.png" },
  { id: 279, name: "056", attribute: "Vitesse", image: baseImageUrl + "056 - Vitesse.png" },
  { id: 280, name: "056", attribute: "Connaissance", image: baseImageUrl + "056 - Connaissance.png" },

  { id: 281, name: "057", attribute: "Technique", image: baseImageUrl + "057 - Technique.png" },
  { id: 282, name: "057", attribute: "Instinct", image: baseImageUrl + "057 - Instinct.png" },
  { id: 283, name: "057", attribute: "Force", image: baseImageUrl + "057 - Force.png" },
  { id: 284, name: "057", attribute: "Vitesse", image: baseImageUrl + "057 - Vitesse.png" },
  { id: 285, name: "057", attribute: "Connaissance", image: baseImageUrl + "057 - Connaissance.png" },

  { id: 286, name: "058", attribute: "Technique", image: baseImageUrl + "058 - Technique.png" },
  { id: 287, name: "058", attribute: "Instinct", image: baseImageUrl + "058 - Instinct.png" },
  { id: 288, name: "058", attribute: "Force", image: baseImageUrl + "058 - Force.png" },
  { id: 289, name: "058", attribute: "Vitesse", image: baseImageUrl + "058 - Vitesse.png" },
  { id: 290, name: "058", attribute: "Connaissance", image: baseImageUrl + "058 - Connaissance.png" },

  { id: 291, name: "059", attribute: "Technique", image: baseImageUrl + "059 - Technique.png" },
  { id: 292, name: "059", attribute: "Instinct", image: baseImageUrl + "059 - Instinct.png" },
  { id: 293, name: "059", attribute: "Force", image: baseImageUrl + "059 - Force.png" },
  { id: 294, name: "059", attribute: "Vitesse", image: baseImageUrl + "059 - Vitesse.png" },
  { id: 295, name: "059", attribute: "Connaissance", image: baseImageUrl + "059 - Connaissance.png" },

  { id: 296, name: "060", attribute: "Technique", image: baseImageUrl + "060 - Technique.png" },
  { id: 297, name: "060", attribute: "Instinct", image: baseImageUrl + "060 - Instinct.png" },
  { id: 298, name: "060", attribute: "Force", image: baseImageUrl + "060 - Force.png" },
  { id: 299, name: "060", attribute: "Vitesse", image: baseImageUrl + "060 - Vitesse.png" },
  { id: 300, name: "060", attribute: "Connaissance", image: baseImageUrl + "060 - Connaissance.png" },

  { id: 301, name: "061", attribute: "Technique", image: baseImageUrl + "061 - Technique.png" },
  { id: 302, name: "061", attribute: "Instinct", image: baseImageUrl + "061 - Instinct.png" },
  { id: 303, name: "061", attribute: "Force", image: baseImageUrl + "061 - Force.png" },
  { id: 304, name: "061", attribute: "Vitesse", image: baseImageUrl + "061 - Vitesse.png" },
  { id: 305, name: "061", attribute: "Connaissance", image: baseImageUrl + "061 - Connaissance.png" },

  { id: 306, name: "062", attribute: "Technique", image: baseImageUrl + "062 - Technique.png" },
  { id: 307, name: "062", attribute: "Instinct", image: baseImageUrl + "062 - Instinct.png" },
  { id: 308, name: "062", attribute: "Force", image: baseImageUrl + "062 - Force.png" },
  { id: 309, name: "062", attribute: "Vitesse", image: baseImageUrl + "062 - Vitesse.png" },
  { id: 310, name: "062", attribute: "Connaissance", image: baseImageUrl + "062 - Connaissance.png" },
]